app/main/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import InputRequired, Email, Length


class ContactForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired(), Length(max=20)])
    email = StringField('Email', validators=[InputRequired(), Email(), Length(max=50)])
    message = TextAreaField('Leave a message', validators=[InputRequired(), Length(max=400)])
    submit = SubmitField('Submit')
    recaptcha = RecaptchaField()

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, flash, current_app
from app.main import bp
from app.main.forms import ContactForm
from app.models import Contact
from app import db
from app.email import send_email


@bp.route('/')
def index():
    return render_template('main/index.html')


@bp.route('/about')
def about():
    return render_template('main/about.html')


def send_contact_email(cont):
    create_date = cont.create_date.strftime('%d/%m/%y %H:%M')
    rec = current_app.config['MAIL_ADMINS']
    return send_email('You have a new message from Arisa via the contact form',
                      sender=current_app.config['MAIL_FROM'],
                      recipients=rec.split(' '),
                      text_body=render_template('main/email_contact.txt', contact=cont, create_date=create_date),
                      html_body=render_template('main/email_contact.html', contact=cont, create_date=create_date))


@bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        cont = Contact(name=form.name.data, email=form.email.data, message=form.message.data)
        db.session.add(cont)
        db.session.commit()
        if send_contact_email(cont):
            flash('Message has been sent!')
        else:
            flash('Sorry system error')
        return redirect(url_for('main.index'))
    return render_template('main/contact.html', form=form)

app/templates/main/about.html
{% extends "base.html" %}

{% block content %}
<div class="col-12">
    <h3>About</h3>
    <p>Something about Arisa</p>
</div>
{% endblock %}

app/templates/main/contact.html
{% extends "base.html" %}
{% block title %}Contact Us{% endblock %}

{% block content %}
<div class="col-12">
    <h3>Contact</h3>

    <p>Send us a message, we will get back to you shortly.</p>
    <form action="{{ url_for('main.contact') }}"  method="post">
        {{ form.csrf_token }}
        <div class="form-row">
            <div class="form-group col-lg-8">
                {{ form.name.label }}
                {% for error in form.name.errors %}
                    <span style="color: red;">[ {{ error }} ]</span><br/>
                {% endfor %}
                {{ form.name(class="form-control") }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-lg-8">
                {{ form.email.label }}
                {% for error in form.email.errors %}
                    <span style="color: red;">[ {{ error }} ]</span><br/>
                {% endfor %}
                {{ form.email(class="form-control") }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-lg-8">
                {{ form.message.label }}
                {% for error in form.message.errors %}
                    <span style="color: red;">[ {{ error }} ]</span><br/>
                {% endfor %}
                {{ form.message(class="form-control", rows=4) }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-lg-8">
                {{ form.recaptcha }}
                {% for error in form.recaptcha.errors %}
                    <span style="color: red;">[ {{ error }} ]</span><br/>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-lg-8">
                {{ form.submit(class="btn btn-md btn-primary") }}
            </div>
        </div>
    </form>

</div>
{% endblock %}

app/templates/main/email_contact.html
<p>You have received a message submitted from the contact form on arisa.com</p>
<p>From: {{ contact.name }}
<p>Email: {{ contact.email }}
<p>Date: {{ create_date }}
<p>Message:</p>
{{ contact.message }}

app/templates/main/index.html
<!-- Home page base template -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Come study in Australia, let's have a chat!">
    <meta name="author" content="Code.Sydney">

    <title>Arisa | Study in Australia</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom Fonts -->
    <link href="{{ url_for('static', filename='fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/stylish-portfolio.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/app.css') }}" type="text/css" rel="stylesheet" >

    <!--needed for flask-moment-->
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
</head>


<body id="page-top" class="bg-primary">

    <!-- Navigation -->
    <a class="menu-toggle rounded" href="#">
        <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a class="js-scroll-trigger" href="{{ url_for('main.index') }}">ARISA</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('main.index') }}">Home</a>
            </li>
            <!--
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('main.about') }}">About</a>
            </li>
            -->
            {% if current_user.is_authenticated %}
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('agent.agent_account') }}">Student Details</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}
            <!--CP_8Aug2019--START Admin Section   -->
            <!-- For Admin role show Admin link-->
            {% if current_user.is_role("admin") %}
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('admin.manage_password') }}">Admin-Reset Password</a>
            </li>
            {% endif %}
            <!--CP_8Aug2019--END Admin Section   -->
            {% if current_user.is_anonymous %}
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            {% endif %}
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="{{ url_for('main.contact') }}">Contact</a>
            </li>
        </ul>
    </nav>

    <!-- Message -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info mb-0 rounded-0" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <!-- Header -->
    <header class="masthead">
        <div class="container text-center my-auto">
            <h1 class="mb-1">Arisa</h1>
            <h3 class="mb-5">
                <em>So you want to study in Australia, let's have a chat</em>
            </h3>
            <!-- Chatbot -->
            <img src="{{ url_for('static', filename='img/chatbot_logo_240x240.png') }}" width="120" height="120">
            <div class="col-12 text-center">
                <iframe
                    allow="microphone;"
                    width="350"
                    height="430"
                    src="https://console.dialogflow.com/api-client/demo/embedded/dec80d74-9e91-434c-bdd1-5d0b82bc7998">
                </iframe>
            </div>
        </div>
    </header>

    <!--
    <div class="bg-light">
        <div class="container">
            <div class="row pt-4 pb-5">
                <div class="col-12 text-center">
                    <h4>Give it a try it is free to use!</h4>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="{{ url_for('main.about') }}">How it works</a>
                </div>
            </div>
        </div>
    </div>
    -->

    <!-- Footer -->
    <div class="container-fluid bg-primary" >
        <div class="row">
            <div class="col-12 mt-4 pt-5">
                <div class="d-flex justify-content-center text-white">
                    <a href="https://www.facebook.com/arisachatbot" target="_blank" class="text-white">
                        <i class="fab fa-2x fa-facebook"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 pt-1 mb-4 pb-5">
                <div class="d-flex justify-content-center text-white">
                    <p class="text-white small mb-0">A Project of <a class="text-white" href="https://www.code.sydney/" target="_blank">Code.Sydney Pty Ltd</a> for <a class="text-white" href="http://www.caloservices.com/" target="_blank" >Calo Services Pty Ltd</a></p>
                </div>
                <div class="d-flex justify-content-center text-white">
                    <p class="text-white small mb-0">Arisa in Alpha version so please read our disclaimer <a class="text-white" href="/static/disclaimer/Arisa_Disclaimer_2019.pdf" target="_blank">here</a></p>
                </div>
            </div>
        </div>
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('static', filename='js/stylish-portfolio.min.js') }}"></script>

</body>
</html>